name: Checks

on:
  pull_request:
    - edited
    - opened
    - reopened

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    name: Check PR Title
    steps:
      - uses: Slashgear/action-check-pr-title@v3.0.0
        with:
          regex: '(revert: )?(chore|feat|fix|test)((.*)): (.*)'