name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.X
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - run: pnpm install
        name: Install dependencies

      - run: pnpm test:ci
        name: Running E2E e2e

  e2e-test:
    needs: build
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: E2E Tests
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install browser
        run: pnpm playwright install --with-deps

      - name: Run Playwright e2e
        run: pnpm playwright test

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
