name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install dependencies
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Build Project
        run: pnpm build

      - run: tar czf output.tar.gz .next

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: output.tar.gz
          retention-days: 1

  lint:
    runs-on: ubuntu-latest
    name: Check Lint
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Check Lint
        run: pnpm lint

  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    name: Unit Tests - Jest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install
        name: Install dependencies

      - run: pnpm test:ci --passWithNoTests
        name: Running Unit tests

  e2e:
    needs: build
    name: E2E Tests - Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: chrome
            browser: chromium
          - project: firefox
            browser: firefox
          - project: safari
            browser: webkit
          - project: android
            browser: chromium
          - project: iphone
            browser: webkit
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'

      - uses: actions/download-artifact@v3
        with:
          name: output
      - run: tar xzf output.tar.gz

      - run: pnpm install
      - run: pnpm playwright install --with-deps ${{ matrix.browser }}
      - run: pnpm playwright test --project=${{ matrix.project }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ matrix.project }}-test-results
          path: playwright-report/
          retention-days: 7
